name: Compile Editor Libraries

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set UE_ROOT
        run: |
          $env:UE_ROOT = "C:\Program Files\Epic Games\UE_5.3"

      - name: Compile Editor Libraries
        run: |
          cmd /c "$env:UE_ROOT\Engine\Build\BatchFiles\Build.bat" DevopsTest Win64 Development -project="C:\Users\User\actions-runner\_work\test_devops\test_devops\DevopsTest.uproject"
